### ISSUE TITLE
Installing VSIX file from Open VSX on VSCodium fails to activate extension

### ISSUE THREAD

**Issue by clin1234** [hieunc229/copilot-clone#15] opened 2021-07-24 17:36 UTC
Probably has something to do with the packaging of the VSIX file. Do you use macOS, by any chance? (`file` on Bash tells me that the node file is a Mach-O binary.

Log:

```
[2021-07-24 13:32:41.566] [exthost] [error] Activating extension captain-stack.captain-stack failed due to an error:
[2021-07-24 13:32:41.566] [exthost] [error] Error: node-loader:
Error: c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\1c6042846227f82725a4e8162b10019a.node is not a valid Win32 application.
c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\1c6042846227f82725a4e8162b10019a.node
	at Object.19571 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:1852305)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.30944 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:19320)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.19520 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:19367)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.54625 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:7344)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.54641 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:1662949)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.58747 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:418416)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.89057 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:1157007)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.98998 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:413174)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.70462 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:613930)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.3164 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:1446428)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.61170 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:323590)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.38868 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:318485)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.16139 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2438967)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.90321 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2440319)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at Object.50112 (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2437467)
	at n (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555206)
	at c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555644
	at Object.<anonymous> (c:\Users\glorious_rise\.vscode-oss\extensions\captain-stack.captain-stack-0.0.2\out\extension.js:2:2555671)
	at Module.u._compile (c:\Program Files\VSCodium\resources\app\out\vs\loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
	at Module.load (internal/modules/cjs/loader.js:935:32)
	at Module._load (internal/modules/cjs/loader.js:776:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.i._load (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:27843)
	at Function.b._load (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:24470)
	at Function.c._load (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:59004)
	at Module.require (internal/modules/cjs/loader.js:959:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (c:\Program Files\VSCodium\resources\app\out\vs\loader.js:5:101)
	at u._loadCommonJSModule (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:25876)
	at u._doActivateExtension (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12556)
	at u._activateExtension (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11657)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)
```

**Comment by Kek5chen** [comment] 2021-07-27 16:01
Duplicate of #11

**Closed as completed by Kek5chen** 2021-07-27 16:01 UTC
Labels: paused
