### ISSUE TITLE
vscode module TypeError

### ISSUE THREAD

**Issue by Darshan25190** [hieunc229/copilot-clone#51] opened 2021-12-21 12:25 UTC
![bugs-in-captain-stack](https://user-images.githubusercontent.com/346605/146929723-f0af78cf-7f35-4a79-84db-e2595c844968.PNG)

**Comment by hieunc229** [comment] 2021-12-22 08:47
Duplicate of #48

**Closed as completed by hieunc229** 2021-12-22 08:47 UTC
