### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by Gianiboy2265** [hieunc229/copilot-clone#52] opened 2022-01-04 10:32 UTC
![Unbenannt](https://user-images.githubusercontent.com/86840255/148046002-6805741b-b3c6-4aa5-92e2-293a7f616f1e.PNG)

**Comment by Gianiboy2265** [comment] 2022-01-04 10:33
Hey. I followed step by step the youtube video. And it started normally. But after I wanted to try the example find sentence or now a custom sentence there comes this error up.

**Comment by Gianiboy2265** [comment] 2022-01-04 10:33
If you need any more things just let me know! :)
I hope you wirte back soon

**Comment by asim1425** [comment] 2022-01-04 11:45
Try This: Work For Me (:
Add This Code: process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'; 
into line no 2 in src/utils/fetchPageContent.ts file
(Sorry For Bad English)

**Comment by Gianiboy2265** [comment] 2022-01-04 11:52
hey I tried that and it worked for me. After 3 or 4 succesfull minutes. Capitain Stack doesn't find results anymore.

**Comment by Gianiboy2265** [comment] 2022-01-04 12:04
![Unbenannt1](https://user-images.githubusercontent.com/86840255/148056473-2ee72653-7a08-4397-bb7e-788e261d3898.PNG)

**Comment by Gianiboy2265** [comment] 2022-01-04 12:04
This is the only error for me atm

**Comment by asim1425** [comment] 2022-01-04 12:39
Did You Run npm install ?

**Comment by Gianiboy2265** [comment] 2022-01-04 13:04
yep

**Comment by Gianiboy2265** [comment] 2022-01-04 13:04
I even re installed the whole thing

**Comment by Gianiboy2265** [comment] 2022-01-04 13:04
and again the same issue

**Comment by asim1425** [comment] 2022-01-04 15:25
Sorry, Idk About This Error

**Comment by hieunc229** [comment] 2022-01-05 00:19
Hey @Gianiboy2265. 

It's Typescript errors. Different versions of Typescript might have different errors as well. 
Can you ignore the errors and start debugging?

**Comment by Gianiboy2265** [comment] 2022-01-05 10:05
yes I can

**Comment by Gianiboy2265** [comment] 2022-01-05 10:05
I just wondered bc when I first started the co-pilot the error wasn't there

**Comment by hieunc229** [comment] 2022-01-05 13:12
When you install the dependencies, it'll download the latest `vscode-dts` automatically. It includes the definition for `vscode` module. The VSCode editor will start to read the type definition and through those errors.

Since the type definition for `vscode-dts` changes quite frequently (because Captain Stack uses an experimental API), updating code to fix those type errors will be outdated in a matter of weeks.

I'll close this thread since seems like the issue is resolved.

**Comment by hieunc229** [comment] 2022-01-05 13:13
Duplicated of #45 and #48

**Closed as completed by hieunc229** 2022-01-05 13:12 UTC

**Comment by hieunc229** [comment] 2022-01-05 13:14
Duplicate of #45 and #48

**Comment by hieunc229** [comment] 2022-01-05 13:14
Duplicate of #45
